import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

const roboto = localFont({
  src: [
    {
      path: "./fonts/Roboto-Black.ttf",
      weight: "400",
    },
    {
      path: "./fonts/Roboto-Regular.ttf",
      weight: "400",
    },
    {
      path: "./fonts/Roboto-Bold.ttf",
      weight: "700",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
